#!/bin/bash
set -e

src=$(pwd)
cd ../adk/lmsbmp

tmp="$(mktemp -d --tmpdir bmp.XXX)"
here="$(pwd)"
cd "$tmp"

cp "$src"/"$1".xbm bitmap.bmp

gcc -I. -o bitmapconverter "$here/bitmapconverter.c"
chmod +x bitmapconverter
./bitmapconverter
mv bitmap.rgf "$src"/"$2".rgf
rm bitmap.bmp
rm bitmapconverter
cd -
rmdir "$tmp"
